In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
titanic = pd.read_csv('train.csv')

In [5]:
titanic = titanic.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'] , axis = 'columns')

In [9]:
titanic

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [10]:
input = titanic.drop('Survived' , axis = 'columns')
output = titanic['Survived']

In [11]:
input

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [12]:
output

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [14]:
label = LabelEncoder()

In [15]:
label.fit(titanic['Sex'])


LabelEncoder()

In [16]:
label.transform(input['Sex'])

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,

In [17]:
input['Sex'] = label.transform(input['Sex'])

In [18]:
input

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [19]:
output

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [21]:
input.columns[input.isna().any()]

Index(['Age'], dtype='object')

In [30]:
input

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [32]:
input.fillna(input['Age'].mean())

Pclass  Sex        Age     Fare
0         3    1  22.000000   7.2500
1         1    0  38.000000  71.2833
2         3    0  26.000000   7.9250
3         1    0  35.000000  53.1000
4         3    1  35.000000   8.0500
..      ...  ...        ...      ...
886       2    1  27.000000  13.0000
887       1    0  19.000000  30.0000
888       3    0  29.699118  23.4500
889       1    1  26.000000  30.0000
890       3    1  32.000000   7.7500

[891 rows x 4 columns]

In [59]:
x_train , x_test , y_train , y_test = train_test_split(input ,output , train_size  =0.8)

In [37]:
len(x_train)

712

In [38]:
len(x_test)

179

In [39]:
from sklearn.naive_bayes import GaussianNB

In [58]:
input = input.fillna(input['Age'].mean())

In [80]:
x_train , x_test , y_train , y_test = train_test_split(input ,output , train_size  =0.8)

In [81]:
model = GaussianNB()
model.fit(x_train,y_train)
model.predict(x_test)

model.score(x_test,y_test)

0.770949720670391

In [52]:
input.isna().value_counts()

Pclass  Sex    Age    Fare 
False   False  False  False    891
dtype: int64

In [61]:
input

Pclass  Sex        Age     Fare
0         3    1  22.000000   7.2500
1         1    0  38.000000  71.2833
2         3    0  26.000000   7.9250
3         1    0  35.000000  53.1000
4         3    1  35.000000   8.0500
..      ...  ...        ...      ...
886       2    1  27.000000  13.0000
887       1    0  19.000000  30.0000
888       3    0  29.699118  23.4500
889       1    1  26.000000  30.0000
890       3    1  32.000000   7.7500

[891 rows x 4 columns]

In [57]:
input.Age.isna()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [62]:
model.predict(x_test)

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1], dtype=int64)

In [67]:
model.predict_proba(x_test)

array([[7.04367803e-01, 2.95632197e-01],
       [9.46698999e-01, 5.33010008e-02],
       [7.45837742e-01, 2.54162258e-01],
       [6.53888090e-01, 3.46111910e-01],
       [3.40016747e-01, 6.59983253e-01],
       [9.66113778e-01, 3.38862216e-02],
       [4.34731485e-01, 5.65268515e-01],
       [9.64635321e-01, 3.53646787e-02],
       [2.55304979e-01, 7.44695021e-01],
       [2.40746603e-01, 7.59253397e-01],
       [9.63710054e-01, 3.62899456e-02],
       [2.92684734e-01, 7.07315266e-01],
       [9.66054258e-01, 3.39457422e-02],
       [9.67450580e-01, 3.25494204e-02],
       [9.67998696e-01, 3.20013040e-02],
       [4.43594683e-01, 5.56405317e-01],
       [9.66794602e-01, 3.32053977e-02],
       [4.43539043e-01, 5.56460957e-01],
       [6.93503309e-01, 3.06496691e-01],
       [9.66486430e-01, 3.35135696e-02],
       [9.64918815e-01, 3.50811848e-02],
       [4.28316584e-01, 5.71683416e-01],
       [9.07379496e-01, 9.26205040e-02],
       [9.63361750e-01, 3.66382504e-02],
       [2.347182

In [68]:
model.score(x_test,y_test)

0.770949720670391

In [82]:
input = titanic.drop('Survived' , axis = 'columns')
output = titanic['Survived']

In [83]:
input

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [84]:
dummies = pd.get_dummies(input.Sex)

In [85]:
dummies

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [86]:
input = pd.concat([input,dummies] , axis ='columns')

In [88]:
input.drop('Sex' , axis = 'columns', inplace = True)


In [90]:
input = input.fillna(input.Age.mean())

In [109]:
x_train , x_test , y_train , y_test = train_test_split(input ,output , train_size  =0.8)

In [110]:
model = GaussianNB()
model.fit(x_train,y_train)
model.predict(x_test)

model.score(x_test,y_test)

0.7486033519553073

In [114]:
# spam classifier
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [124]:
spam = pd.read_csv('Downloads/spam.csv')

In [125]:
spam

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [127]:
spam

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [126]:
x_train , x_test , y_train, y_test = train_test_split(spam.Message , spam.spam , train_size = 0.8 )

AttributeError: 'DataFrame' object has no attribute 'spam'

In [128]:
spam

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [131]:
spam['spam'] = spam.Category.apply(lambda x : 1 if x == 'spam' else 0)

In [138]:
spam.groupby('Category').describe()

spam                                   
           count mean  std  min  25%  50%  75%  max
Category                                           
ham       4825.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam       747.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [139]:
spam.drop('Category' , axis = 'columns' , inplace = True)


In [141]:
x_train , x_test , y_train, y_test = train_test_split(spam.Message , spam.spam , train_size = 0.8 )

In [142]:
x_train

3631    Get the official ENGLAND poly ringtone or colo...
2413    I don't know u and u don't know me. Send CHAT ...
4421                      Ok i msg u b4 i leave my house.
104     wow. You're right! I didn't mean to do that. I...
1420    Speak only when you feel your words are better...
                              ...                        
3194    I will lick up every drop :) are you ready to ...
513                               Lol ok your forgiven :)
3741              No da. . Vijay going to talk in jaya tv
4476                    We will meet soon princess! Ttyl!
1682                                               Y lei?
Name: Message, Length: 4457, dtype: object

In [143]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [146]:
x_train_count = v.fit_transform(x_train.values)

In [152]:
x_train_count.toarray()

(4457, 7720)

In [157]:
x_train_count

<4457x7720 sparse matrix of type '<class 'numpy.int64'>'
	with 59514 stored elements in Compressed Sparse Row format>

In [154]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [158]:
model.fit(x_train_count , y_train)

MultinomialNB()

In [165]:
spam[spam['spam'] == 1]

Message  spam
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
5     FreeMsg Hey there darling it's been 3 week's n...     1
8     WINNER!! As a valued network customer you have...     1
9     Had your mobile 11 months or more? U R entitle...     1
11    SIX chances to win CASH! From 100 to 20,000 po...     1
...                                                 ...   ...
5537  Want explicit SEX in 30 secs? Ring 02073162414...     1
5540  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...     1
5547  Had your contract mobile 11 Mnths? Latest Moto...     1
5566  REMINDER FROM O2: To get 2.50 pounds free call...     1
5567  This is the 2nd time we have tried 2 contact u...     1

[747 rows x 2 columns]

In [162]:
v.transform(['Pls confirm the time to collect the cheque.'])

<1x7720 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [167]:
model.predict(v.transform(['WINNER!! As a valued network customer you have.',
                          'Pls confirm the time to collect the cheque.']))

array([1, 0], dtype=int64)

In [170]:
model.predict(v.transform(x_test))

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [171]:
model.score(v.transform(x_test) , y_test)

0.9928251121076234

In [1]:
from sklearn.datasets import load_wine

In [2]:
wine = load_wine()

In [3]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [4]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [179]:
df = pd.DataFrame(wine.data , columns = wine.feature_names)

In [183]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [186]:
df.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [187]:
scaler = MinMaxScaler()
scaler.fit(df[['proline']])

df['proline'] = scaler.transform(df[['proline']])


In [190]:
df.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [191]:
scaler = MinMaxScaler()
scaler.fit(df[['magnesium']])

df['magnesium'] = scaler.transform(df[['magnesium']])

In [192]:
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6   0.619565           2.80   
1      13.20        1.78  2.14               11.2   0.326087           2.65   
2      13.16        2.36  2.67               18.6   0.336957           2.80   
3      14.37        1.95  2.50               16.8   0.467391           3.85   
4      13.24        2.59  2.87               21.0   0.521739           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5   0.271739           1.68   
174    13.40        3.91  2.48               23.0   0.347826           1.80   
175    13.27        4.28  2.26               20.0   0.543478           1.59   
176    13.17        2.59  2.37               20.0   0.543478           1.65   
177    14.13        4.10  2.74               24.5   0.282609           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines   proline  
0                            3.92  0.561341  
1                            3.40  0.550642  
2                            3.17  0.646933  
3                            3.45  0.857347  
4                            2.93  0.325963  
..                            ...       ...  
173                          1.74  0.329529  
174                          1.56  0.336662  
175                          1.56  0.397290  
176                          1.62  0.400856  
177                          1.60  0.201141  

[178 rows x 13 columns]

In [193]:
x_test , x_test ,y_train , y_test = train_test_split(df , wine.target , train_size = 0.8)

In [194]:
x_test

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
99     12.29        3.17  2.21               18.0   0.195652           2.85   
96     11.81        2.12  2.74               21.5   0.695652           1.60   
107    12.72        1.75  2.28               22.5   0.152174           1.38   
164    13.78        2.76  2.30               22.0   0.217391           1.35   
54     13.74        1.67  2.25               16.4   0.521739           2.60   
132    12.81        2.31  2.40               24.0   0.304348           1.15   
9      13.86        1.35  2.27               16.0   0.304348           2.98   
161    13.69        3.26  2.54               20.0   0.402174           1.83   
92     12.69        1.53  2.26               20.7   0.108696           1.38   
8      14.83        1.64  2.17               14.0   0.293478           2.80   
126    12.43        1.53  2.29               21.5   0.173913           2.74   
12     13.75        1.73  2.41               16.0   0.206522           2.60   
89     12.08        1.33  2.30               23.6   0.000000           2.20   
4      13.24        2.59  2.87               21.0   0.521739           2.80   
46     14.38        3.59  2.28               16.0   0.347826           3.25   
61     12.64        1.36  2.02               16.8   0.326087           2.02   
52     13.82        1.75  2.42               14.0   0.445652           3.88   
120    11.45        2.40  2.42               20.0   0.282609           2.90   
166    13.45        3.70  2.60               23.0   0.445652           1.70   
148    13.32        3.24  2.38               21.5   0.239130           1.93   
156    13.84        4.12  2.38               19.5   0.206522           1.80   
18     14.19        1.59  2.48               16.5   0.413043           3.30   
75     11.66        1.88  1.92               16.0   0.293478           1.61   
17     13.83        1.57  2.62               20.0   0.489130           2.95   
170    12.20        3.03  2.32               19.0   0.282609           1.25   
134    12.51        1.24  2.25               17.5   0.163043           2.00   
81     12.72        1.81  2.20               18.8   0.173913           2.20   
23     12.85        1.60  2.52               17.8   0.271739           2.48   
84     11.84        0.89  2.58               18.0   0.260870           2.20   
35     13.48        1.81  2.41               20.5   0.326087           2.70   
67     12.37        1.17  1.92               19.6   0.086957           2.11   
70     12.29        1.61  2.21               20.4   0.358696           1.10   
38     13.07        1.50  2.10               15.5   0.304348           2.40   
100    12.08        2.08  1.70               17.5   0.293478           2.23   
122    12.42        4.43  2.73               26.5   0.347826           2.20   
90     12.08        1.83  2.32               18.5   0.119565           1.60   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity  \
99         2.99                  0.45             2.81             2.30   
96         0.99                  0.14             1.56             2.50   
107        1.76                  0.48             1.63             3.30   
164        0.68                  0.41             1.03             9.58   
54         2.90                  0.21             1.62             5.85   
132        1.09                  0.27             0.83             5.70   
9          3.15                  0.22             1.85             7.22   
161        0.56                  0.50             0.80             5.88   
92         1.46                  0.58             1.62             3.05   
8          2.98                  0.29             1.98             5.20   
126        3.15                  0.39             1.77             3.94   
12         2.76                  0.29             1.81             5.60   
89         1.59                  0.42             1.38             1.74   
4          2.69                

In [195]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [196]:
model.fit(x_train , y_train)
model.predict(x_test)
model.score(x_test, y_test)

ValueError: could not convert string to float: 'Get the official ENGLAND poly ringtone or colour flag on yer mobile for tonights game! Text TONE or FLAG to 84199. Optout txt ENG STOP Box39822 W111WX £1.50'